name: Deploy Pages
on:
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
    
    
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:
      - name: Test GH
        run: |
          gh run list