name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node_modules
        uses: actions/cache@v3
        id: node_modules-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - name: Cache firebase emulators
        uses: actions/cache@v3
        id: firebase-cache
        with:
          path: ~/.cache/firebase/emulators/
          key: ${{ runner.os }}-firebase-${{ hashFiles('**/package-lock.json') }}

      - if: steps.node_modules-cache.outputs.cache-hit != 'true'
        name: Install dependencies
        run: npm ci
      - if: steps.playwright-cache.outputs.cache-hit != 'true'
        name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v1
      - name: Run Playwright tests
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        run: CI=true npx playwright test --reporter=html
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
